db:
    build: db/
    ports: 
        - "5432:5432"

back-end:
    build: back-end/
    environment:
        - dws_environment=compose
    ports:
        - "8080:8080"
    links:
        - db
        
front-end:
    build: front-end/
    environment:
        - dws_api_proxy=dws_back-end_1:8080
    ports:
        - "80:80"
    links:
        - back-end